name: Workflow 2 - Print Java Installed Message

on:
  workflow_run:
    workflows: ["Check Java Installation"]
    types:
      - completed

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Print Java Installed Message
        run: echo "Yes, Java is installed!"
