name: Work_Flow_1
on:
  workflow_dispatch:
  workflow_call:

jobs:
  work-flow-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print message
        run: echo "Work FLow 1"
      
  trigger-workflow1:
   needs: work-flow-1
   uses: ./.github/workflows/Work_Flow_2.yml
