name: Workflow 2 - Print Java Installed Message

on:
  workflow_run:
    workflows: ["Check Java Installation"]
    types:
      - completed

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Print Java Installed Message
        run: echo "Yes, Java is installed!"
        
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Trigger Workflow 1 Again
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ./.github/workflows/check-java.yml
        with:
          Default: ${{ github.repository }}
