name: Work_Flow_2

on:
  workflow_call:

jobs:
  work-flow-2:
    runs-on: ubuntu-latest
    steps:
      - name: Work Flow 2 Running
        run: echo "I'm Work Flow 2."
  t-wf-1:
   needs: work-flow-2
   uses: ./.github/workflows/Work_Flow_1.yml
