name: Workflow 2

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true

jobs:
  workflow2_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say I'm Fine
        run: echo "Yes, I'm fine, ${{ github.event.inputs.name }}!"
