name: Workflow 1

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true

jobs:
  Workflow_1_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, ${{ github.event.inputs.name }}!"
      - name: Trigger Workflow 2
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const resp = await octokit.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Workflow 2',
              ref: context.sha,
              inputs: {
                name: '${{ github.event.inputs.name }}'
              }
            });
            console.log(resp);
